inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml
  
# Railsに特化したCopを実行するための設定
Rails:
  Enabled: true


# 以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'
    
    

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false
  
# Line is too long を無視
Metrics/LineLength:
  Enabled: false
